import json
import os
from pathlib import Path

Import('env')  # noqa: F821 - SConscript-style pre-script import

ROOT = Path(env.subst('$PROJECT_DIR'))
SECRETS_JSON = ROOT / 'mqtt_secrets.json'
OUTPUT_HEADER = ROOT / 'src' / 'secrets.h'

# Public-safe fallbacks: host/topic are not secrets, user/pass are empty so
# a build without mqtt_secrets.json simply cannot authenticate.
DEFAULTS = {
    'broker': '65604cba457d4f8992aefe5820219ae4.s1.eu.hivemq.cloud',
    'port': 8883,
    'tls': True,
    'user': '',
    'pass': '',
    'topic': 'skyspy',
}


def q(s):
    return '"%s"' % str(s).replace('"', '\\"')


def main():
    data = dict(DEFAULTS)
    if SECRETS_JSON.is_file():
        try:
            with open(SECRETS_JSON) as f:
                data.update({k: v for k, v in json.load(f).items() if k in DEFAULTS})
        except Exception as e:
            print('gen_secrets: failed to read %s: %s' % (SECRETS_JSON, e))

    lines = [
        '// AUTO-GENERATED by scripts/gen_secrets.py - DO NOT EDIT',
        '// MQTT defaults come from the gitignored mqtt_secrets.json.',
        '#pragma once',
        '#define SECRET_MQTT_HOST %s' % q(data['broker']),
        '#define SECRET_MQTT_PORT %d' % int(data['port']),
        '#define SECRET_MQTT_TLS  %d' % (1 if bool(data['tls']) else 0),
        '#define SECRET_MQTT_USER %s' % q(data['user']),
        '#define SECRET_MQTT_PASS %s' % q(data['pass']),
        '#define SECRET_MQTT_TOPIC %s' % q(data['topic']),
        '',
    ]
    OUTPUT_HEADER.write_text('\n'.join(lines))
    print('gen_secrets: wrote %s (secrets file present: %s)'
          % (OUTPUT_HEADER.name, SECRETS_JSON.is_file()))


main()
